### PR TITLE
Implement `Hit` union type

### PR DESCRIPTION
**Pull request by neryortez**
Implements a `Hit` type that lets the user have `objectID` property on results as well [as their own properties](https://www.typescriptlang.org/play/#src=type%20Hit%3CT%20%3D%20%7B%7D%3E%20%3D%20T%20%26%20%7B%20objectID%3A%20string%20%7D%3B%0D%0A%0D%0Ainterface%20MyObject%20%7B%0D%0A%20%20%20%20prop1%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20hit%3A%20Hit%3CMyObject%3E%3B%0D%0Alet%20hit2%3A%20Hit%3B%0D%0A%0D%0Ahit.objectID%3B%0D%0Ahit.prop1%3B%0D%0A%0D%0A%2F%2F%20It%20still%20lets%20you%20use%20objectID%0D%0Ahit2.objectID%3B%0D%0A%2F%2F%20And%20gives%20error%20when%20props%20don't%20exist%0D%0Ahit.anotherProp%3B%0D%0Ahit2.a%3B%20%0D%0A).

Use would be:
```
index.browse<MyObject>(/*arguments*/);
index.search<MyObject>(/*arguments*/);
// or it can also be left empty
index.browse(/*arguments*/);
index.search(/*arguments*/);
```

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by squirly** [comment]
I do not think this is a good approach, it is not typesafe. Instead users should validate the recieved data instead of casting using a generic. If casting is desired, it should be done explicitly:
`hit as any as T`

Casting is okay in application code where assumptions are known, but in libraries typings should make minimal assumptions and strive for correctness.

**Comment by neryortez** [comment]
@KSaryan , @squirly 
Please check the update. Now the user can have clean inferred types.

See working example [here.](https://stackblitz.com/edit/typescript-zxbtbj)

**Comment by squirly** [comment]
The `T` here is still unbounded (uninferrable) in this example. The change just obscures that a bit.

**Comment by neryortez** [comment]
I think I'm not understanding.

Could you please give an example where `T` cannot be inferred correctly?

**Comment by squirly** [comment]
I cannot give an example because it can never be inferred.

If you do not explicitly define the generic, it will always use the default. Which means it is unbounded.

This pattern is fine in application code but not suitable for a library.

Related lint rule https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/

**Comment by neryortez** [comment]
I get it now..! :D
There's a language barrier.

What I'm trying to say is that with the current state of @KSaryan's fork you should always use
```hit as any as T```.
 The same goes for what I'm proposing _if you do not use generics_.

In these case, when you're casting, you should be aware that `objectID` is being added by Algolia. It may not be on your expected type. Thus `as any as T` will be wrong if  ` T`  doesn't have `objectID`.


The advantage comes when you know for sure what the response would look like. You can use generics.... And `objectID` will be there added to `T`.

Again, if you don't use generics, it will do as you say: use the default. But is okay, as the default is the same as proposed in this fork.
Yes, it's a bit obscure. You're right. But these approach gives a more real sense of what is happening.

What are your thoughts?
Also, I would like to hear from you @KSaryan.

**Pull request closed without merging**
